/**
 * Yagona ikonka manbai: Ionicons (iOS uslubidagi yupqa kontur ikonkalar, MIT litsenziya) `react-icons/io5` orqali.
 * Komponentlar ikonkalarni shu yerdan oladi, shuning uchun to`plamni almashtirish bitta fayl.
 * (Apple SF Symbols litsenziyasi veb-saytda ishlatishga ruxsat bermaydi.)
 */
export type { IconType as Icon } from "react-icons";

export {
  IoArrowDownOutline as ArrowDown,
  IoArrowBackOutline as ArrowLeft,
  IoArrowForwardOutline as ArrowRight,
  IoArrowUpOutline as ArrowUp,
  IoPulseOutline as AudioLines,
  IoCheckmarkCircle as BadgeCheck,
  IoBanOutline as Ban,
  IoNotificationsOutline as Bell,
  IoBriefcaseOutline as Briefcase,
  IoBusinessOutline as Building2,
  IoTimeOutline as CalendarClock,
  IoCalendarOutline as CalendarDays,
  IoCalendarNumberOutline as CalendarPlus,
  IoCheckmark as Check,
  IoCheckmark as CheckIcon,
  IoCheckmarkDoneOutline as CheckCheck,
  IoChevronDown as ChevronDown,
  IoChevronDown as ChevronDownIcon,
  IoChevronBack as ChevronLeft,
  IoChevronForward as ChevronRight,
  IoChevronForward as ChevronRightIcon,
  IoChevronUp as ChevronUpIcon,
  IoCheckmarkCircleOutline as CircleCheckIcon,
  IoClipboardOutline as ClipboardList,
  IoTimeOutline as Clock,
  IoDownloadOutline as Download,
  IoOpenOutline as ExternalLink,
  IoEyeOutline as Eye,
  IoEyeOffOutline as EyeOff,
  IoDocumentTextOutline as FileText,
  IoCloudUploadOutline as FileUp,
  IoFolderOpenOutline as FolderOpen,
  IoGlobeOutline as Globe,
  IoFileTrayOutline as Inbox,
  IoInformationCircleOutline as InfoIcon,
  IoLanguageOutline as Languages,
  IoGridOutline as LayoutGrid,
  IoListOutline as List,
  IoReloadOutline as Loader2Icon,
  IoLockClosedOutline as Lock,
  IoLockOpenOutline as LockOpen,
  IoLogOutOutline as LogOut,
  IoMailOutline as Mail,
  IoLocationOutline as MapPin,
  IoMenuOutline as Menu,
  IoMicOutline as Mic,
  IoMicOutline as Mic2,
  IoMusicalNotesOutline as Music,
  IoCloseCircleOutline as OctagonXIcon,
  IoPencilOutline as Pencil,
  IoCreateOutline as PenLine,
  IoCallOutline as Phone,
  IoMoon as Moon,
  IoPause as Pause,
  IoPlay as Play,
  IoAdd as Plus,
  IoSearchOutline as Search,
  IoSendOutline as Send,
  IoShieldCheckmarkOutline as ShieldCheck,
  IoShuffleOutline as Shuffle,
  IoOptionsOutline as SlidersHorizontal,
  IoSparklesOutline as Sparkles,
  IoSunny as Sun,
  IoTrashOutline as Trash2,
  IoWarningOutline as TriangleAlert,
  IoWarningOutline as TriangleAlertIcon,
  IoCloudUploadOutline as Upload,
  IoPersonAddOutline as UserPlus,
  IoPersonOutline as UserRound,
  IoPeopleOutline as Users,
  IoPeopleOutline as UsersRound,
  IoVideocamOffOutline as VideoOff,
  IoWalletOutline as Wallet,
  IoColorWandOutline as Wand2,
  IoClose as X,
  IoClose as XIcon,
  IoCloseCircleOutline as XCircle,
} from "react-icons/io5";

export {
  IoStatsChartOutline as BarChart3,
  IoLayersOutline as FolderTree,
  IoSpeedometerOutline as Gauge,
  IoImageOutline as Image,
  IoHomeOutline as LayoutDashboard,
  IoNewspaperOutline as Newspaper,
  IoReaderOutline as ScrollText,
  IoSettingsOutline as Settings,
  IoTrophyOutline as Trophy,
} from "react-icons/io5";

/* ===== To'ldirilgan (filled) iOS uslubidagi variantlar: tab-bar faol holati, ilova ikonkasi kafellari ===== */
import type { IconType } from "react-icons";
import {
  IoBriefcase,
  IoBusiness,
  IoClipboard,
  IoCreate,
  IoHome,
  IoImage,
  IoLayers,
  IoMail,
  IoMic,
  IoMusicalNotes,
  IoNewspaper,
  IoNotifications,
  IoPeople,
  IoPerson,
  IoPulse,
  IoReader,
  IoSearch,
  IoSettings,
  IoShieldCheckmark,
  IoSparkles,
  IoSpeedometer,
  IoStatsChart,
  IoTrophy,
} from "react-icons/io5";
import {
  IoBriefcaseOutline,
  IoBusinessOutline,
  IoClipboardOutline,
  IoCreateOutline,
  IoHomeOutline,
  IoImageOutline,
  IoLayersOutline,
  IoMailOutline,
  IoMicOutline,
  IoMusicalNotesOutline,
  IoNewspaperOutline,
  IoNotificationsOutline,
  IoPeopleOutline,
  IoPersonOutline,
  IoPulseOutline,
  IoReaderOutline,
  IoSearchOutline,
  IoSettingsOutline,
  IoShieldCheckmarkOutline,
  IoSparklesOutline,
  IoSpeedometerOutline,
  IoStatsChartOutline,
  IoTrophyOutline,
} from "react-icons/io5";

export {
  IoBriefcase as BriefcaseFill,
  IoBusiness as BuildingFill,
  IoCreate as PenLineFill,
  IoMic as MicFill,
  IoMusicalNotes as MusicFill,
  IoPeople as UsersFill,
  IoPulse as AudioLinesFill,
  IoSparkles as SparklesFill,
};

const OUTLINE_TO_FILL = new Map<IconType, IconType>([
  [IoBriefcaseOutline, IoBriefcase],
  [IoBusinessOutline, IoBusiness],
  [IoClipboardOutline, IoClipboard],
  [IoCreateOutline, IoCreate],
  [IoHomeOutline, IoHome],
  [IoImageOutline, IoImage],
  [IoLayersOutline, IoLayers],
  [IoMailOutline, IoMail],
  [IoMicOutline, IoMic],
  [IoMusicalNotesOutline, IoMusicalNotes],
  [IoNewspaperOutline, IoNewspaper],
  [IoNotificationsOutline, IoNotifications],
  [IoPeopleOutline, IoPeople],
  [IoPersonOutline, IoPerson],
  [IoPulseOutline, IoPulse],
  [IoReaderOutline, IoReader],
  [IoSearchOutline, IoSearch],
  [IoSettingsOutline, IoSettings],
  [IoShieldCheckmarkOutline, IoShieldCheckmark],
  [IoSparklesOutline, IoSparkles],
  [IoSpeedometerOutline, IoSpeedometer],
  [IoStatsChartOutline, IoStatsChart],
  [IoTrophyOutline, IoTrophy],
]);

/** Kontur ikonkaning to'ldirilgan juftini qaytaradi (topilmasa o'zini) */
export function filled(icon: IconType): IconType {
  return OUTLINE_TO_FILL.get(icon) ?? icon;
}
